<!-- Banner-->
<table border="1" width="80%">
 <tr>
  <td>
      <a href="index.php"><img src="imagens/banner.png" width="50%"></a>
  </td>
  <td align="right" valign="bottom">
      <p class="texto1">
        <a href="index.php">Início</a>| 
		<a href="cadastro.php">Cadastrar</a> | 
		<a href="pesquisa.php">Pesquisar</a> | 
		<a href="altera.php">Alterar</a> | 
        <a href="exclui.php">Excluir</a>
      </p>
   </td>
  </tr>
</table>  
 <hr> 

