<!-- Área de trabalho -->
 <h3 class="titulo">Sistema de controle de coleções</h3>
 <table border='1'>
    <tr>
		<td width='70%' class="texto2">O SysHQs é um sistema para controle de coleções de HQS 
		                desenvolvido em HTML 5, CSS 3, PHP e MySQL.
		</td>
		<td width='30%'>
		 <a href='http://www.amazon.com.br'>Amazon</a></p>
		 <a href='http://www.saraiva.com.br'>Saraiva</a></p>
		 <a href='http://www.ovicio.com.br'>O Vício</a></p>
		 <a href='http://www.guiadosquadrinhos.com'>Guia dos Quadrinhos</a></p>
		 <a href='https://br.norton.com/internetsecurity-emerging-threats-what-is-social-engineering.html'>
		  O que é Engenharia Social</a></p>
		</td>
	</tr>
 </table> 
 <hr>